#! /bin/sh

# Autostart
# ==============================================
sxhkd &
polybar -c ~/.config/polybar/config.ini main &
compton &
conky ~/.config/conky/conky.conf &

# Set wallpaper, and terminal theme
# ==============================================
wal -i ~/.config/wallpaper.jpg &

# BSPWM monitor workspaces
# =============================================
bspc monitor -d i II III IV V

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
