#! /bin/sh

# Autostart
# ========================================
sxhkd &
compton &
sh ~/.config/conky/launch.sh &
sh ~/.config/polybar/launch.sh &

# Set wallpaper, and terminal theme
feh --bg-scale ~/.config/wallpaper.jpg &
# wal -i ~/.config/wallpaper.jpg & # Deprecated because decided on gruvbox colorcheme(do not want to change Xresources file) 

# Set monitor orientation
xrandr --output DVI-D-2 --primary --auto --output DVI-D-1 --right-of DVI-D-2 --auto

# BSPWM monitor workspaces
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DVI-D-2 -d I II III IV V
bspc monitor DVI-D-1 -d VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true


##  bspc rule -a firefox desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
